# Generated by Django 3.2.9 on 2022-06-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('expense_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpedidospendiente',
            name='idPersona',
        ),
        migrations.RemoveField(
            model_name='pedidospendiente',
            name='idPersona',
        ),
        migrations.AddField(
            model_name='pedidospendiente',
            name='idPersona',
            field=models.ManyToManyField(to='users.User', verbose_name='Identificador de la Persona'),
        ),
    ]
