# Generated by Django 3.2.9 on 2022-06-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallescompra',
            name='estadoCompra',
            field=models.CharField(default='', max_length=30, verbose_name='Estado de la Compra'),
        ),
        migrations.AlterField(
            model_name='historicaldetallescompra',
            name='estadoCompra',
            field=models.CharField(default='', max_length=30, verbose_name='Estado de la Compra'),
        ),
        migrations.AlterField(
            model_name='historicalpedidospendiente',
            name='estadoPedido',
            field=models.CharField(default='', max_length=30, verbose_name='Estado del Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidospendiente',
            name='estadoPedido',
            field=models.CharField(default='', max_length=30, verbose_name='Estado del Pedido'),
        ),
    ]
