# Generated by Django 3.2.9 on 2022-06-14 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpromocion',
            name='idProducto',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.producto', verbose_name='Identificar del Producto'),
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='idProducto',
        ),
        migrations.AddField(
            model_name='promocion',
            name='idProducto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.producto', verbose_name='Identificar del Producto'),
        ),
    ]
