# Generated by Django 3.2.9 on 2022-06-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpromocion',
            name='idProducto',
        ),
        migrations.RemoveField(
            model_name='historicalpromocion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='destacado',
            field=models.CharField(default='DE', max_length=30, verbose_name='Tipo del Producto'),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='estadoProducto',
            field=models.BooleanField(default=False, verbose_name='Estado de la Promocion'),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='tiempoProducto',
            field=models.CharField(default='NUE', max_length=30, verbose_name='Tiempo del Producto'),
        ),
        migrations.AlterField(
            model_name='historicalpromocion',
            name='estadoPromocion',
            field=models.CharField(default='ACT', max_length=30, verbose_name='Estado de la Promocion'),
        ),
        migrations.AlterField(
            model_name='historicalpromocion',
            name='tiempoPromocion',
            field=models.CharField(default='NUE', max_length=30, verbose_name='Tiempo de la Promocion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='destacado',
            field=models.CharField(default='DE', max_length=30, verbose_name='Tipo del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estadoProducto',
            field=models.BooleanField(default=False, verbose_name='Estado de la Promocion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tiempoProducto',
            field=models.CharField(default='NUE', max_length=30, verbose_name='Tiempo del Producto'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='estadoPromocion',
            field=models.CharField(default='ACT', max_length=30, verbose_name='Estado de la Promocion'),
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='idProducto',
        ),
        migrations.AddField(
            model_name='promocion',
            name='idProducto',
            field=models.ManyToManyField(default='', to='products.Producto', verbose_name='Identificar del Producto'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='tiempoPromocion',
            field=models.CharField(default='NUE', max_length=30, verbose_name='Tiempo de la Promocion'),
        ),
    ]
