# Generated by Django 3.2.9 on 2022-06-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220605_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpromocion',
            name='estadoPromocion',
            field=models.CharField(default='', max_length=30, verbose_name='Estado de la Promocion'),
        ),
        migrations.AddField(
            model_name='historicalpromocion',
            name='fechaFinalizacion',
            field=models.DateField(null=True, verbose_name='Fecha de Finalizacion'),
        ),
        migrations.AddField(
            model_name='historicalpromocion',
            name='fechaInicio',
            field=models.DateField(null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AddField(
            model_name='historicalpromocion',
            name='tiempoPromocion',
            field=models.CharField(default='', max_length=30, verbose_name='Tiempo de la Promocion'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='estadoPromocion',
            field=models.CharField(default='', max_length=30, verbose_name='Estado de la Promocion'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='fechaFinalizacion',
            field=models.DateField(null=True, verbose_name='Fecha de Finalizacion'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='fechaInicio',
            field=models.DateField(null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='tiempoPromocion',
            field=models.CharField(default='', max_length=30, verbose_name='Tiempo de la Promocion'),
        ),
    ]
