# Generated by Django 3.2.9 on 2022-06-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220624_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducto',
            name='fechaFinalizacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Finalizacion'),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fechaFinalizacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Finalizacion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
    ]
